---
title: "Analysis of finance-related Reddit Communities"
output: rmdformats::readthedown
bibliography: references.bib
csl: ieee.csl

---

# Overview and Motivation

In January of 2021, a major short squeeze of the stock of video game retailer GameStop and other securities took place[@RePEc]. A major driving force behind this event was the subreddit wallstreetbets, where users discussed the market situation around GameStop, focussing on the amount of short positions major hedge funds held for this stock and a “David versus Goliath”-situation unfolded. What followed was a large influx of users to the subreddit, who were convinced the stock had to go up and hedge funds had to pay for it. 
 
Several interesting questions regarding the influence of these subreddits on the stock market emerge from this event. In this project, we want to detect communities in finance related subreddits and mine their sentiment towards discussed stocks to measure if they either have significant influence on or can predict market movements.

# Related Work 

Prediction of market movements in relation to stock prices and volume of traded stocks has been widely studied mainly because it can be used as a tool for  investing in profitable stocks with small risks. The prediction of stock prices has been carried out with different machine learning  techniques [@8212715].



# Initial Questions

Based on the objectives on our proposal, the initial questions that we tried to solve were divided in three aspects of our project, which are data extraction and storage, community detection, sentiment analysis, and correlation between sentiment and stock market information. The questions are as follows: 
 
1. How can we create communities inside subreddits and extract the stocks discussed inside each community?
2. Is it possible to correlate the sentiment towards the stocks discussed in each community to  the stock market related data?

The questions evolved during the first stages of data collecting and research about algorithms for clustering and sentiment analysis. The questions change into more specific and new questions were included. The final questions for the project are:

### 1. How can we identify subcommunities inside subreddit and which measures can be used to evaluate the subcommunities?
A subreddit is already a big community inside Reddit, which allows the interaction between users. It is important to represent the interaction from the users in order to find relations and smaller clusters from users which we can analyze afterwards.  

### 2. Is it possible to identify stocks that are discussed in each subcommunity and the sentiment related to the stocks in a specific point of time?

### 3. Based on the stocks and sentiments towards them inside the communities, is it possible to find a correlation with the stock prices?

# Data

*source, scraping method, cleanup, storage, etc.*

For this project we have two main sources of data, namely Reddit and Yahoo Finance. 

## Reddit comments
The data that we use from the subreddits are comments on posts and the post content. For this purpose we used the library RedditExtractoR and extract daily the comments on the posts with more than 20 comments. We got the data from 11.01.2020 for the subreddits "Wallstreetbets" and "stocks"

## Stock data

## Feature engineering

# Exploratory Data Analysis

*What visualizations did you use to look at your data in different ways?*
*What are the different machine learning methods you considered?*
*Justify the decisions you made, and show any major changes to your ideas.*
*How did you reach these conclusions?*

# Final Analysis

*What did you learn about the data?*
*How did you answer the questions?*
*How can you justify your answers?*

# References
