---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r setup}
library(tidyverse)
library(sentimentr)
library(quantmod)
library(BatchGetSymbols)
library(plotly)
source("DB_connection.R")
```

Loading Data. No connection the database right now?
```{r eval=F}
content <- financedb
```
```{r}
content <- loadData("reddit", "stocks")
```

Adding ticker column. TODO: Make lists of ticker by observation possible
"I bought AMC and BB" -> c("AMC", "BB")

Using sentiment_by because fast

```{r demo}
stringr::str_match_all("I bought AMC and BB", '[^A-Za-z0-9]+([A-Z]{2,4})[^A-Za-z0-9]*')[[1]][,2]
sentiment_by("It's hot outside, but I quite enjoy it. My plants are dying still")
```

```{r}
dat <- content %>%
  mutate(ticker = stringr::str_match(comment, '[^A-Za-z0-9]*([A-Z]{2,4})[^A-Za-z0-9]*')[,2],
         sentiment = sentiment_by(get_sentences(comment))$ave_sentiment)
head(dat %>% na.omit() %>% select(ticker, sentiment))
```

Getting the sentiment for the 15 most discussed tickers TODO: Blacklist YOLO, THE, WSB
```{r}
ticker_sentiment <- dat %>% 
  group_by(ticker) %>%
  summarise(count=n(), sentiment_ticker=mean(sentiment, na.rm = T)) %>%
  arrange(desc(count)) %>%
  na.omit() %>%
  head(15)
ticker_sentiment
```

getting market data for top 5 discussed tickers (FAST and Chached)

```{r}
tickers <- ticker_sentiment$ticker %>% head(5)
l.out <- BatchGetSymbols(tickers = tickers, 
                         first.date = min(dat$comm_date),
                         last.date = max(dat$comm_date), 
                         freq.data = "daily",
                         cache.folder = file.path(tempdir(), 
                                                  'BGS_Cache'))
```

```{r}
dat_tmp <- dat %>%
  group_by("date" = lubridate::date(comm_date), ticker) %>%
  summarise(sentiment=mean(sentiment),
            vol_sentiment = n(),
            upvote_prop = mean(upvote_prop, na.rm = T))
```

```{r}
symbol <- "GME"
fig1 <- l.out$df.tickers %>%
  filter(ticker==symbol) %>%
  plot_ly(x = ~ref.date, type="candlestick",
          open = ~price.open, close = ~price.close,
          high = ~price.high, low = ~price.low) %>%
  layout(xaxis = list(rangeslider = list(visible = F)))

ay <- list(
  overlaying = "y2",
  side = "right"
)

fig2 <- dat_tmp %>%
  filter(ticker==symbol) %>%
  plot_ly() %>%
  add_trace(x=~date, y=~sentiment, name="sentiment", type="scatter", line=list(color="#00000"), mode="line")

fig3 <- dat_tmp %>%
  filter(ticker==symbol) %>%
  plot_ly() %>%
  add_trace(x=~date, y=~vol_sentiment, name="vol_sentiment", type="bar")



subplot(fig1, fig2, fig3, nrows=3, shareX = T)
```



```{r}
plot_ticker_sentiment <- function(reddit_data, market_data, ticker) {
  plot_lst <- list()
  for (t in ticker){
    p <- ggplot
  }
}
```




